### ISSUE TITLE
When generating assets.in, '\' character not escaped in Windows

### ISSUE THREAD

**Issue by ark-** [andrew-lucker/Lattice#1] opened 2017-06-07 12:14 UTC
Noticed when compiling Premadeath on Windows 7 x64.

Assets.in are generated with paths such as:

`[("assets\textures\avatar\ant\facedownleftfoot.png",include_bytes! "assets\textures\avatar\ant\facedownleftfoot.png").to_vec()),`

When they should be:

`[("assets\\textures\\avatar\\ant\\facedownleftfoot.png",include_bytes! "assets\\textures\\avatar\\ant\\facedownleftfoot.png").to_vec()),
`

I fixed this using a local version of lattice where I added the following line to build.rs

`let path = path.replace("\\", "\\\\");`

Maybe this can be switched based on the compilation architecture.

Incidentally, the Lattice example uses forward slashes which are less of a problem for Windows and might actually work better than '\\'.

**Comment by andrew-lucker** [comment] 2017-06-07 17:20
I'm not really sure what the best practice for paths on Windows is nowadays. Would you recommend the full escaped '\\' or conditional forward slashes for windows?

**Comment by andrew-lucker** [comment] 2017-06-07 19:29
This issue should now be mostly fixed by deferring to Rust std::path::Path entirely. There is one exception for the case of examples, which don't have their own build script. I tried making one build.rs script for the project to generate the assets file, but have not confirmed the examples working on Windows yet.

**Comment by andrew-lucker** [comment] 2017-06-08 19:42
Confirmed fixed after [installing SDL2 on Windows](https://github.com/AngryLawyer/rust-sdl2#windows-with-build-script), which turns out to be much more difficult than would be desirable. Also, there is an external dynamic library that needs to be distributed along with the binary...

Closing this issue, but opening another for possibly using a different backend for Windows.

**Closed by andrew-lucker** 2017-06-08 19:42 UTC
Labels: bug

**Comment by ark-** [comment] 2017-06-09 13:00
Sorry it took so long to get back. Glad you figured it out.
